openapi: "3.0.0"
info:
  title: T shirt store API
  description: API for Ecommmerce Store
  version: 1.1.0
  contact:
    email: manasranjanmurmu@gmail.com
    url: "https://localhost.com"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: for localhost - secure
#   - url: "http://localhost:4000/api/v1"
#     description: for localhost - regular

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for localhost - secure
    variables:
      version:
        enum:
          - v1
          - v2
      protocol:
        enum:
          - http
          - https

components:
  securitySchemes:
    cookieAuth:
      type: apikey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /lco:
    get:
      tags:
        - Home
      summary: return a Greet Message from Manas
      responses:
        200:
          description: All Goood and Success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
